### ISSUE TITLE
Shader compilation error

### ISSUE THREAD

**Issue by Rameron** [Rinnegatamante/AvP-Gold-Vita#3]
Hello.

I installed the game with the valid data from AvP Gold. Then I used ShaRKF00D for extracting libshacccg.suprx. But when I'm starting the game I see the black screen. And there are an error "vertex shader compilation failed" in "ux0:/data/AvP.log". The file "libshacccg.suprx" exists in ur0:/data.

How can I solve this issue?

**Comment by Rinnegatamante** [comment]
Rename ur0:data, create the folder from scratch and put inside it libshacccg.suprx.
