### ISSUE TITLE
Invert look 

### ISSUE THREAD

**Issue by russ840** [Rinnegatamante/AvP-Gold-Vita#5]
Hi. 

Is there anyway to invert the look on right stick? 

Many thanks.

**Comment by Rinnegatamante** [comment]
You could do it via reVita plugin.

**Comment by russ840** [comment]
Ok. Sounds interesting. Can I get that from auto plug-in ?

**Comment by russ840** [comment]
I did this last night. Works a treat. Thank you for the advice
